site_name: 'gitlab-test'
site_description: 'Main documentation for gitlab-test'
repo_url: https://github.com/tyrelof/gitlab-test
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started: 'docs/index.md'