redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

global:
  domain: argocd.test.com

certificate:
  enabled: true

server:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    enabled: true
    ingressClassName: nginx
    tls: true

# ⬇️ RBAC + admin account enable
configEnabled: true
config:
  accounts.admin: login
bacConfig:
  policy.matchMode: glob
  scopes: '[groups]'
  policy.csv: |
    g, admin, role:admin
  policy.default: role:readonly